### ISSUE TITLE
Tracking not working on iOS 14

### ISSUE THREAD

**Issue by caieu** [hypertrack/sdk-react-native#16] opened 2020-10-05 19:23 UTC
Hi!

I'm trying to use the package, I already updated to the newest version, and I'm able to track on Android 11 and 8, and also on iOS 12. But when I'm testing on iOS 14, I can't get the tracking working properly. 

I can see my device on the dashboard but shows only at the inactive tab, with the status `Tracking stopped`.

I'm using the QuickStart example.

**Comment by tulushev** [comment] 2020-10-05 19:27
Hi @caieu, can you paste your device_id?
Do you use the SDK's `start()` method to start tracking or an API call?

**Comment by caieu** [comment] 2020-10-05 19:38
My device id: `F9C263F0-B182-4345-BB13-73C3FC565601`
and i'm using this function right after registering the tracking listeners: `this.hyperTrack.startTracking()`

**Comment by tulushev** [comment] 2020-10-05 19:40
Can you try starting the device from Playground/API call?

**Comment by caieu** [comment] 2020-10-05 19:48
yes, when I use the API, I got this response `{"message": "Device tracking started"}`.

then, when I see the list of devices, I can see on the inactive tab with this status now `Push notification token missing`, and when I hit the details button, shows this status `Unknown outage`.

I already set up the auth key and the team id on the setup screen.

**Comment by tulushev** [comment] 2020-10-05 19:54
I see that push notifications were integrated and device itself has a token. Trying to figure out why dashboard shows this status. Does it persist when you refresh the page?

**Comment by caieu** [comment] 2020-10-05 19:57
Yes, it persist and also using the incognito tab.

**Comment by tulushev** [comment] 2020-10-05 19:57
Can you restart the app? Probably it got in a bad state because of manual tracking. Filing this internally to investigate.

**Comment by caieu** [comment] 2020-10-05 20:29
yes, I tried a couple of times, but I got the same status.

**Comment by caieu** [comment] 2020-10-05 21:59
I tried to remove the `startTracking` function call, and start tracking through the API, and now shows the device under the `Disconnected` tab.

**Comment by charleskoehl** [comment] 2020-10-06 05:03
I found that after I build and run in Xcode to my iPhone with iOS 14.0.1, I can get tracking to start by switching to any other app and back.

**Comment by DmitryShapovalov** [comment] 2020-10-06 12:34
@caieu Hello. Using HyperTrack with push notifications integration, manual start/stop tracking is not recommended. Please try reinstall the host app and make API call startTracking. The might resolve SDK bad state.

**Comment by tulushev** [comment] 2020-10-06 16:59
To expand and summarise:
* Current native SDKs have a new feature called "Automatic Sync" [introduced in 4.4.0](https://github.com/hypertrack/sdk-ios/releases/tag/4.4.0). It allows the SDK to start and stop tracking more reliably with API based controls when push notifications fail.
* This feature is in conflict with manual start/stop tracking issued directly from SDKs. Manual tracking was deprecated for a while and we don't officially mention it in our docs. Our customers use only API based or trip based tracking.
* Recently we found a new usecase for manual tracking in our own app, so we are adding compatibility of "Automatic Sync" with manual tracking. That's what @DmitryShapovalov is mentioning as a fix. But I still think that you should only use API or trip based tracking for your use case anyway. It's more reliable and controllable.

@caieu @charleskoehl can you remove manual tracking (`startTracking()` calls), delete the app, wait for a minute (iOS has inconsistencies with permissions when you quickly reinstall apps) and then install the new version and try starting tracking from API and see if the issue is resolved?

**Comment by caieu** [comment] 2020-10-06 18:22
I removed the `startTracking`, delete the app, restarted my ipad (mini 2 ios 12), then installed again. 

After that, my ipad were only showed at the `Playground` screen, and not at `Views` screen. Then, I tried to `startTracking` on the `Playground` screen, but my device was shown at the  `Views` screen as `Disconnected`.

Then I hit the ipad home button, close the app from the background, and open again. Now I can see my device on the `Active` tab.

When I used the `startTracking` function on the ipad mini 2, showed up at the `Views` screen on the `Active` tab right after giving the permissions.

**Comment by tulushev** [comment] 2020-10-06 19:02
@caieu this means that push notification didn't reach the device, but automatic sync called our platform and started tracking. The app going to background is one of the automatic sync triggers. It can be a push notification issue:
- either OS didn't give the device_token to the app
- the device had background app refresh disabled or low power mode enabled
- maybe there is a problem with push notification setup or with push processing on our side.

What was the device_id of this device? I'll check our push logs.

**Comment by tulushev** [comment] 2020-10-06 20:00
@caieu I looked at iPad mini with device_id `5308D51B-6A2E-4227-9756-2015DADD5CE0` and it has a permissions problem, where location and motion permissions were not requested by the app.

**Comment by caieu** [comment] 2020-10-06 20:03
this is my most recent device id for the iPad `0296D677-8DC4-436C-AD1F-7231F260875B`

**Comment by tulushev** [comment] 2020-10-06 20:09
@caieu looks like tracking is working on this device_id. Does this iPad have cellular? I don't see a network operator.

**Comment by caieu** [comment] 2020-10-06 20:14
no, only wifi. Yes, now it's tracking but i had to close the app and open again. I had to do this after removing the `startTracking` function.

**Comment by caieu** [comment] 2020-10-06 20:16
I had to add the `react-native-permissions` package to ask for the activity and location permissions. It's needed? for ios, the permission dialog does not appear.

**Comment by tulushev** [comment] 2020-10-06 20:26
`0296D677-8DC4-436C-AD1F-7231F260875B` started tracking at `2020-10-06T18:11:28.266Z` UTC because of push notification. Probably push notification reached the device, but maybe a bit late, and opening/closing the app just coincided with OS receiving a push.

Regarding devices we support, we support all iPhones and cellular iPads listed here https://en.wikipedia.org/wiki/Apple_motion_coprocessors#Products

Non-cellular models and are not officially supported, because we can't guarantee tracking without GPS.

**Comment by caieu** [comment] 2020-10-06 20:38
Yes, I'm using the latest RN wrapper. It was false the second parameter. Will test with true.

**Comment by tulushev** [comment] 2020-10-07 14:20
Hi @caieu , was the issue resolved?

**Comment by caieu** [comment] 2020-10-07 14:59
Not yet, but we're making more tests with the package. The main problem was with the ios 14, but we're going to test in more devices.

**Comment by tulushev** [comment] 2020-10-07 15:17
Got it. There shouldn't be any problems when using REST API to start/stop tracking. iOS 14 shouldn't affect this. There can be a push notification delay when starting / stopping tracking using REST API, but automatic sync reduces this delay by syncing up with our platform when the following happens:
* App brought to foreground
* App brought to background
* App launched
* Publishable key is set
* Every 30 minutes during active tracking

Also @DmitryShapovalov released RN wrapper 7.0.1, which should fix RN compatibility issue related to Podspecs, please make sure that you are using this version.

If there are any problems, reach out here or in Slack. Device IDs are usually the first thing we need when debugging a case.

**Closed** 2020-11-18 15:14 UTC
